name: files update workflow

on:
  schedule:
    # every day at 05:30 UTC the job will run
    - cron: "30 5 * * *"
  push:
    branches:
      - master

jobs:
  update_files:
    runs-on: ubuntu-latest
    timeout-minutes: 9

    steps:
      - uses: actions/checkout@v2
      - name: Load Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: Run Script
        run: |
          pip install download
          python update_files.py
          echo "the job completed"

      - name: Push to Github
        run: |
          bash ./main.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Push to Heroku
        run: |+
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login ${{secrets.HEROKU_EMAIL}}
              password ${{secrets.HEROKU_API_KEY}}
          machine git.heroku.com
              login ${{secrets.HEROKU_EMAIL}}
              password ${{secrets.HEROKU_API_KEY}}
          EOF
          heroku git:remote -a ${{secrets.HEROKU_APP_NAME}}
          git pull
          git push heroku master
          echo "Successfully Deployed"
